name: 'Return details of assigned issues'
description: 'A custom Github action to return details of issues assigned to a user'

inputs:
  username:
    description: 'The name of the user whose issues you want to return'
    required: true
  access-token:
    description: 'The access token that the action will use to authenticate in a REST API request'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args: 
    - ${{ inputs.username }}
    - ${{ inputs.access-token }}